<?php
$page_title='Edit Anggota'; $active_page='anggota'; $body_restrict='admin'; include '../includes/header.php'; require_once '../includes/koneksi.php';
$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT); if(!$id){$_SESSION['flash']=['type'=>'error','message'=>'ID anggota tidak valid.'];header('Location: list.php');exit;}
$stmt=$pdo->prepare('SELECT * FROM anggota WHERE id=:id');$stmt->execute([':id'=>$id]);$anggota=$stmt->fetch();if(!$anggota){$_SESSION['flash']=['type'=>'error','message'=>'Data anggota tidak ditemukan.'];header('Location: list.php');exit;}
$old=$_SESSION['old_edit_anggota']??$anggota;$errors=$_SESSION['form_errors_edit_anggota']??[];unset($_SESSION['old_edit_anggota'],$_SESSION['form_errors_edit_anggota']);function e($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
?>
<main class="container"><a href="list.php" class="back-link"><i class="fa-solid fa-arrow-left"></i> Kembali ke Daftar Anggota</a><div class="form-card"><h2 class="form-card-title">Edit Data Anggota</h2><p class="form-card-desc">Perbarui informasi anggota di bawah ini.</p>
<form action="proses_edit.php" method="post" novalidate><input type="hidden" name="id" value="<?= (int)$id ?>"><div class="form-grid">
<?php foreach([['id_anggota','ID Anggota','Contoh: AG-103','text',false],['telepon','Nomor Telepon / WA','08xxxxxxxxxx','tel',false],['nama','Nama Lengkap','Masukkan nama lengkap anggota','text',true],['email','Alamat Email','contoh@domain.com','email',true]] as [$name,$label,$placeholder,$type,$full]):$err=$errors[$name]??'';?><div class="form-group<?= $err?' has-error':'' ?><?= $full?' full-width':'' ?>"><label for="<?=$name?>"><?=$label?></label><input type="<?=$type?>" id="<?=$name?>" name="<?=$name?>" value="<?=e($old[$name]??'')?>" placeholder="<?=e($placeholder)?>"<?=$err?' aria-invalid="true"':''?> required><?php if($err):?><small class="form-error"><?=e($err)?></small><?php endif;?></div><?php endforeach;?>
<?php $err=$errors['alamat']??'';?><div class="form-group full-width<?= $err?' has-error':'' ?>"><label for="alamat">Alamat Tinggal</label><textarea id="alamat" name="alamat" rows="2" placeholder="Alamat lengkap..."><?=e($old['alamat']??'')?></textarea><?php if($err):?><small class="form-error"><?=e($err)?></small><?php endif;?></div>
<?php $err=$errors['status']??'';?><div class="form-group<?= $err?' has-error':'' ?>"><label for="status">Status</label><select id="status" name="status"><option value="Aktif"<?=($old['status']??'')==='Aktif'?' selected':''?>>Aktif</option><option value="Non-Aktif"<?=($old['status']??'')==='Non-Aktif'?' selected':''?>>Non-Aktif</option></select><?php if($err):?><small class="form-error"><?=e($err)?></small><?php endif;?></div>
</div><div class="form-actions"><a href="list.php" class="btn-cancel">Batal</a><button type="submit" class="btn-submit"><i class="fa-solid fa-floppy-disk"></i> Simpan Perubahan</button></div></form></div></main><?php include '../includes/footer.php'; ?>
