FROM dunglas/frankenphp:1-php8.2-alpine

HEALTHCHECK NONE

RUN install-php-extensions pdo_pgsql pgsql

WORKDIR /app

COPY Caddyfile /etc/caddy/Caddyfile
COPY . /app

ENV PORT=80

CMD ["frankenphp", "run", "--config", "/etc/caddy/Caddyfile"]
